title: The Cyclotron Project
author:
  name: Reed Michael Upson & Ray Anchordoquy
  email: thecyclotronproject@gmail.com
description: Est. 2018, flinging protons around since 2023 (hopefully). 
repository: thecyclotronproject/thecyclotronproject.github.io

url: https://thecyclotronproject.github.io
baseurl: ""

permalink: pretty

# Build settings
remote_theme: jekyll/minima

show_excerpts: false
# Hey Reed, add pages here, you need to create markdown files for each one. It's YAML, so just follow the format.
header_pages:
  - Gallery.md
  - vacuum.md
  - magnets.md
  - updates.md
  - ion.md
  - thanks.md
plugins:
  - jekyll-feed
  - jekyll-remote-theme
minima:
  skin: dark
